// flow-typed signature: b6f73c0c3859c2e1f264b0d51606058c
// flow-typed version: <<STUB>>/apollo-codegen_v0.10.13/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-codegen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-codegen' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-codegen/lib/cli' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/compilation' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/downloadSchema' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/errors' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/flow/codeGeneration' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/flow/index' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/flow/language' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/flow/types' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/generate' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/index' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/introspectSchema' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/loading' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/printSchema' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/serializeToJSON' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/swift/codeGeneration' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/swift/index' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/swift/language' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/swift/types' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/swift/values' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/typescript/codeGeneration' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/typescript/index' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/typescript/language' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/typescript/types' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/utilities/CodeGenerator' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/utilities/graphql' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/utilities/printing' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/validation' {
  declare module.exports: any;
}

declare module 'apollo-codegen/test/compilation' {
  declare module.exports: any;
}

declare module 'apollo-codegen/test/flow/codeGeneration' {
  declare module.exports: any;
}

declare module 'apollo-codegen/test/introspectSchema' {
  declare module.exports: any;
}

declare module 'apollo-codegen/test/swift/codeGeneration' {
  declare module.exports: any;
}

declare module 'apollo-codegen/test/swift/language' {
  declare module.exports: any;
}

declare module 'apollo-codegen/test/swift/types' {
  declare module.exports: any;
}

declare module 'apollo-codegen/test/typescript/codeGeneration' {
  declare module.exports: any;
}

declare module 'apollo-codegen/test/validation' {
  declare module.exports: any;
}

declare module 'apollo-codegen/test/valueFromValueNode' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-codegen/lib/cli.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/cli'>;
}
declare module 'apollo-codegen/lib/compilation.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/compilation'>;
}
declare module 'apollo-codegen/lib/downloadSchema.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/downloadSchema'>;
}
declare module 'apollo-codegen/lib/errors.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/errors'>;
}
declare module 'apollo-codegen/lib/flow/codeGeneration.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/flow/codeGeneration'>;
}
declare module 'apollo-codegen/lib/flow/index.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/flow/index'>;
}
declare module 'apollo-codegen/lib/flow/language.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/flow/language'>;
}
declare module 'apollo-codegen/lib/flow/types.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/flow/types'>;
}
declare module 'apollo-codegen/lib/generate.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/generate'>;
}
declare module 'apollo-codegen/lib/index.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/index'>;
}
declare module 'apollo-codegen/lib/introspectSchema.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/introspectSchema'>;
}
declare module 'apollo-codegen/lib/loading.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/loading'>;
}
declare module 'apollo-codegen/lib/printSchema.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/printSchema'>;
}
declare module 'apollo-codegen/lib/serializeToJSON.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/serializeToJSON'>;
}
declare module 'apollo-codegen/lib/swift/codeGeneration.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/swift/codeGeneration'>;
}
declare module 'apollo-codegen/lib/swift/index.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/swift/index'>;
}
declare module 'apollo-codegen/lib/swift/language.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/swift/language'>;
}
declare module 'apollo-codegen/lib/swift/types.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/swift/types'>;
}
declare module 'apollo-codegen/lib/swift/values.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/swift/values'>;
}
declare module 'apollo-codegen/lib/typescript/codeGeneration.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/typescript/codeGeneration'>;
}
declare module 'apollo-codegen/lib/typescript/index.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/typescript/index'>;
}
declare module 'apollo-codegen/lib/typescript/language.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/typescript/language'>;
}
declare module 'apollo-codegen/lib/typescript/types.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/typescript/types'>;
}
declare module 'apollo-codegen/lib/utilities/CodeGenerator.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/utilities/CodeGenerator'>;
}
declare module 'apollo-codegen/lib/utilities/graphql.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/utilities/graphql'>;
}
declare module 'apollo-codegen/lib/utilities/printing.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/utilities/printing'>;
}
declare module 'apollo-codegen/lib/validation.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/validation'>;
}
declare module 'apollo-codegen/test/compilation.js' {
  declare module.exports: $Exports<'apollo-codegen/test/compilation'>;
}
declare module 'apollo-codegen/test/flow/codeGeneration.js' {
  declare module.exports: $Exports<'apollo-codegen/test/flow/codeGeneration'>;
}
declare module 'apollo-codegen/test/introspectSchema.js' {
  declare module.exports: $Exports<'apollo-codegen/test/introspectSchema'>;
}
declare module 'apollo-codegen/test/swift/codeGeneration.js' {
  declare module.exports: $Exports<'apollo-codegen/test/swift/codeGeneration'>;
}
declare module 'apollo-codegen/test/swift/language.js' {
  declare module.exports: $Exports<'apollo-codegen/test/swift/language'>;
}
declare module 'apollo-codegen/test/swift/types.js' {
  declare module.exports: $Exports<'apollo-codegen/test/swift/types'>;
}
declare module 'apollo-codegen/test/typescript/codeGeneration.js' {
  declare module.exports: $Exports<'apollo-codegen/test/typescript/codeGeneration'>;
}
declare module 'apollo-codegen/test/validation.js' {
  declare module.exports: $Exports<'apollo-codegen/test/validation'>;
}
declare module 'apollo-codegen/test/valueFromValueNode.js' {
  declare module.exports: $Exports<'apollo-codegen/test/valueFromValueNode'>;
}
