// flow-typed signature: de1c0658a7bab4b53488b813b12bff10
// flow-typed version: <<STUB>>/apollo-codegen_v0.19.1/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-codegen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-codegen' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-codegen/lib/__tests__/__fixtures__/commentedOut' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/__tests__/__fixtures__/comments' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/__tests__/__fixtures__/invalid' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/__tests__/__fixtures__/normal' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/__tests__/loading' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/cli' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/compiler/index' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/compiler/legacyIR' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/compiler/visitors/collectAndMergeFields' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/compiler/visitors/collectFragmentsReferenced' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/compiler/visitors/generateOperationId' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/compiler/visitors/inlineRedundantTypeConditions' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/compiler/visitors/typeCase' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/downloadSchema' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/errors' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/flow/codeGeneration' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/flow/index' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/flow/language' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/flow/types' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/generate' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/index' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/introspectSchema' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/javascript/flow/__tests__/codeGeneration' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/javascript/flow/__tests__/helpers' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/javascript/flow/codeGeneration' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/javascript/flow/helpers' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/javascript/flow/index' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/javascript/flow/language' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/javascript/flow/printer' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/javascript/types/augment-babel-types' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/javascript/types/babel7' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/javascript/typescript/__tests__/codeGeneration' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/javascript/typescript/__tests__/helpers' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/javascript/typescript/codeGeneration' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/javascript/typescript/helpers' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/javascript/typescript/index' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/javascript/typescript/language' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/javascript/typescript/printer' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/loading' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/polyfills' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/printSchema' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/scala/codeGeneration' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/scala/index' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/scala/language' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/scala/naming' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/scala/types' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/scala/values' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/serializeToJSON' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/swift/codeGeneration' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/swift/helpers' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/swift/index' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/swift/language' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/typescript/codeGeneration' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/typescript/index' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/typescript/language' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/typescript/types' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/utilities/array' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/utilities/CodeGenerator' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/utilities/graphql' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/utilities/printing' {
  declare module.exports: any;
}

declare module 'apollo-codegen/lib/validation' {
  declare module.exports: any;
}

declare module 'apollo-codegen/src/__tests__/__fixtures__/commentedOut' {
  declare module.exports: any;
}

declare module 'apollo-codegen/src/__tests__/__fixtures__/comments' {
  declare module.exports: any;
}

declare module 'apollo-codegen/src/__tests__/__fixtures__/invalid' {
  declare module.exports: any;
}

declare module 'apollo-codegen/src/__tests__/__fixtures__/normal' {
  declare module.exports: any;
}

declare module 'apollo-codegen/src/cli' {
  declare module.exports: any;
}

declare module 'apollo-codegen/src/flow/codeGeneration' {
  declare module.exports: any;
}

declare module 'apollo-codegen/src/flow/index' {
  declare module.exports: any;
}

declare module 'apollo-codegen/src/flow/language' {
  declare module.exports: any;
}

declare module 'apollo-codegen/src/flow/types' {
  declare module.exports: any;
}

declare module 'apollo-codegen/src/polyfills' {
  declare module.exports: any;
}

declare module 'apollo-codegen/src/scala/codeGeneration' {
  declare module.exports: any;
}

declare module 'apollo-codegen/src/scala/index' {
  declare module.exports: any;
}

declare module 'apollo-codegen/src/scala/language' {
  declare module.exports: any;
}

declare module 'apollo-codegen/src/scala/naming' {
  declare module.exports: any;
}

declare module 'apollo-codegen/src/scala/types' {
  declare module.exports: any;
}

declare module 'apollo-codegen/src/scala/values' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-codegen/lib/__tests__/__fixtures__/commentedOut.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/__tests__/__fixtures__/commentedOut'>;
}
declare module 'apollo-codegen/lib/__tests__/__fixtures__/comments.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/__tests__/__fixtures__/comments'>;
}
declare module 'apollo-codegen/lib/__tests__/__fixtures__/invalid.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/__tests__/__fixtures__/invalid'>;
}
declare module 'apollo-codegen/lib/__tests__/__fixtures__/normal.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/__tests__/__fixtures__/normal'>;
}
declare module 'apollo-codegen/lib/__tests__/loading.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/__tests__/loading'>;
}
declare module 'apollo-codegen/lib/cli.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/cli'>;
}
declare module 'apollo-codegen/lib/compiler/index.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/compiler/index'>;
}
declare module 'apollo-codegen/lib/compiler/legacyIR.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/compiler/legacyIR'>;
}
declare module 'apollo-codegen/lib/compiler/visitors/collectAndMergeFields.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/compiler/visitors/collectAndMergeFields'>;
}
declare module 'apollo-codegen/lib/compiler/visitors/collectFragmentsReferenced.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/compiler/visitors/collectFragmentsReferenced'>;
}
declare module 'apollo-codegen/lib/compiler/visitors/generateOperationId.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/compiler/visitors/generateOperationId'>;
}
declare module 'apollo-codegen/lib/compiler/visitors/inlineRedundantTypeConditions.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/compiler/visitors/inlineRedundantTypeConditions'>;
}
declare module 'apollo-codegen/lib/compiler/visitors/typeCase.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/compiler/visitors/typeCase'>;
}
declare module 'apollo-codegen/lib/downloadSchema.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/downloadSchema'>;
}
declare module 'apollo-codegen/lib/errors.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/errors'>;
}
declare module 'apollo-codegen/lib/flow/codeGeneration.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/flow/codeGeneration'>;
}
declare module 'apollo-codegen/lib/flow/index.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/flow/index'>;
}
declare module 'apollo-codegen/lib/flow/language.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/flow/language'>;
}
declare module 'apollo-codegen/lib/flow/types.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/flow/types'>;
}
declare module 'apollo-codegen/lib/generate.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/generate'>;
}
declare module 'apollo-codegen/lib/index.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/index'>;
}
declare module 'apollo-codegen/lib/introspectSchema.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/introspectSchema'>;
}
declare module 'apollo-codegen/lib/javascript/flow/__tests__/codeGeneration.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/javascript/flow/__tests__/codeGeneration'>;
}
declare module 'apollo-codegen/lib/javascript/flow/__tests__/helpers.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/javascript/flow/__tests__/helpers'>;
}
declare module 'apollo-codegen/lib/javascript/flow/codeGeneration.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/javascript/flow/codeGeneration'>;
}
declare module 'apollo-codegen/lib/javascript/flow/helpers.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/javascript/flow/helpers'>;
}
declare module 'apollo-codegen/lib/javascript/flow/index.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/javascript/flow/index'>;
}
declare module 'apollo-codegen/lib/javascript/flow/language.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/javascript/flow/language'>;
}
declare module 'apollo-codegen/lib/javascript/flow/printer.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/javascript/flow/printer'>;
}
declare module 'apollo-codegen/lib/javascript/types/augment-babel-types.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/javascript/types/augment-babel-types'>;
}
declare module 'apollo-codegen/lib/javascript/types/babel7.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/javascript/types/babel7'>;
}
declare module 'apollo-codegen/lib/javascript/typescript/__tests__/codeGeneration.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/javascript/typescript/__tests__/codeGeneration'>;
}
declare module 'apollo-codegen/lib/javascript/typescript/__tests__/helpers.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/javascript/typescript/__tests__/helpers'>;
}
declare module 'apollo-codegen/lib/javascript/typescript/codeGeneration.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/javascript/typescript/codeGeneration'>;
}
declare module 'apollo-codegen/lib/javascript/typescript/helpers.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/javascript/typescript/helpers'>;
}
declare module 'apollo-codegen/lib/javascript/typescript/index.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/javascript/typescript/index'>;
}
declare module 'apollo-codegen/lib/javascript/typescript/language.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/javascript/typescript/language'>;
}
declare module 'apollo-codegen/lib/javascript/typescript/printer.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/javascript/typescript/printer'>;
}
declare module 'apollo-codegen/lib/loading.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/loading'>;
}
declare module 'apollo-codegen/lib/polyfills.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/polyfills'>;
}
declare module 'apollo-codegen/lib/printSchema.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/printSchema'>;
}
declare module 'apollo-codegen/lib/scala/codeGeneration.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/scala/codeGeneration'>;
}
declare module 'apollo-codegen/lib/scala/index.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/scala/index'>;
}
declare module 'apollo-codegen/lib/scala/language.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/scala/language'>;
}
declare module 'apollo-codegen/lib/scala/naming.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/scala/naming'>;
}
declare module 'apollo-codegen/lib/scala/types.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/scala/types'>;
}
declare module 'apollo-codegen/lib/scala/values.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/scala/values'>;
}
declare module 'apollo-codegen/lib/serializeToJSON.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/serializeToJSON'>;
}
declare module 'apollo-codegen/lib/swift/codeGeneration.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/swift/codeGeneration'>;
}
declare module 'apollo-codegen/lib/swift/helpers.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/swift/helpers'>;
}
declare module 'apollo-codegen/lib/swift/index.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/swift/index'>;
}
declare module 'apollo-codegen/lib/swift/language.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/swift/language'>;
}
declare module 'apollo-codegen/lib/typescript/codeGeneration.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/typescript/codeGeneration'>;
}
declare module 'apollo-codegen/lib/typescript/index.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/typescript/index'>;
}
declare module 'apollo-codegen/lib/typescript/language.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/typescript/language'>;
}
declare module 'apollo-codegen/lib/typescript/types.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/typescript/types'>;
}
declare module 'apollo-codegen/lib/utilities/array.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/utilities/array'>;
}
declare module 'apollo-codegen/lib/utilities/CodeGenerator.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/utilities/CodeGenerator'>;
}
declare module 'apollo-codegen/lib/utilities/graphql.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/utilities/graphql'>;
}
declare module 'apollo-codegen/lib/utilities/printing.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/utilities/printing'>;
}
declare module 'apollo-codegen/lib/validation.js' {
  declare module.exports: $Exports<'apollo-codegen/lib/validation'>;
}
declare module 'apollo-codegen/src/__tests__/__fixtures__/commentedOut.js' {
  declare module.exports: $Exports<'apollo-codegen/src/__tests__/__fixtures__/commentedOut'>;
}
declare module 'apollo-codegen/src/__tests__/__fixtures__/comments.js' {
  declare module.exports: $Exports<'apollo-codegen/src/__tests__/__fixtures__/comments'>;
}
declare module 'apollo-codegen/src/__tests__/__fixtures__/invalid.js' {
  declare module.exports: $Exports<'apollo-codegen/src/__tests__/__fixtures__/invalid'>;
}
declare module 'apollo-codegen/src/__tests__/__fixtures__/normal.js' {
  declare module.exports: $Exports<'apollo-codegen/src/__tests__/__fixtures__/normal'>;
}
declare module 'apollo-codegen/src/cli.js' {
  declare module.exports: $Exports<'apollo-codegen/src/cli'>;
}
declare module 'apollo-codegen/src/flow/codeGeneration.js' {
  declare module.exports: $Exports<'apollo-codegen/src/flow/codeGeneration'>;
}
declare module 'apollo-codegen/src/flow/index.js' {
  declare module.exports: $Exports<'apollo-codegen/src/flow/index'>;
}
declare module 'apollo-codegen/src/flow/language.js' {
  declare module.exports: $Exports<'apollo-codegen/src/flow/language'>;
}
declare module 'apollo-codegen/src/flow/types.js' {
  declare module.exports: $Exports<'apollo-codegen/src/flow/types'>;
}
declare module 'apollo-codegen/src/polyfills.js' {
  declare module.exports: $Exports<'apollo-codegen/src/polyfills'>;
}
declare module 'apollo-codegen/src/scala/codeGeneration.js' {
  declare module.exports: $Exports<'apollo-codegen/src/scala/codeGeneration'>;
}
declare module 'apollo-codegen/src/scala/index.js' {
  declare module.exports: $Exports<'apollo-codegen/src/scala/index'>;
}
declare module 'apollo-codegen/src/scala/language.js' {
  declare module.exports: $Exports<'apollo-codegen/src/scala/language'>;
}
declare module 'apollo-codegen/src/scala/naming.js' {
  declare module.exports: $Exports<'apollo-codegen/src/scala/naming'>;
}
declare module 'apollo-codegen/src/scala/types.js' {
  declare module.exports: $Exports<'apollo-codegen/src/scala/types'>;
}
declare module 'apollo-codegen/src/scala/values.js' {
  declare module.exports: $Exports<'apollo-codegen/src/scala/values'>;
}
