// flow-typed signature: 75222e2ab835425c43af53958ac79190
// flow-typed version: <<STUB>>/codemirror-graphql_v0.6.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'codemirror-graphql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'codemirror-graphql' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'codemirror-graphql/hint' {
  declare module.exports: any;
}

declare module 'codemirror-graphql/info' {
  declare module.exports: any;
}

declare module 'codemirror-graphql/jump' {
  declare module.exports: any;
}

declare module 'codemirror-graphql/lint' {
  declare module.exports: any;
}

declare module 'codemirror-graphql/mode' {
  declare module.exports: any;
}

declare module 'codemirror-graphql/results/mode' {
  declare module.exports: any;
}

declare module 'codemirror-graphql/utils/CharacterStream' {
  declare module.exports: any;
}

declare module 'codemirror-graphql/utils/collectVariables' {
  declare module.exports: any;
}

declare module 'codemirror-graphql/utils/forEachState' {
  declare module.exports: any;
}

declare module 'codemirror-graphql/utils/getHintsAtPosition' {
  declare module.exports: any;
}

declare module 'codemirror-graphql/utils/getTokenAtPosition' {
  declare module.exports: any;
}

declare module 'codemirror-graphql/utils/getTypeInfo' {
  declare module.exports: any;
}

declare module 'codemirror-graphql/utils/hintList' {
  declare module.exports: any;
}

declare module 'codemirror-graphql/utils/info-addon' {
  declare module.exports: any;
}

declare module 'codemirror-graphql/utils/jsonParse' {
  declare module.exports: any;
}

declare module 'codemirror-graphql/utils/jump-addon' {
  declare module.exports: any;
}

declare module 'codemirror-graphql/utils/objectValues' {
  declare module.exports: any;
}

declare module 'codemirror-graphql/utils/onlineParser' {
  declare module.exports: any;
}

declare module 'codemirror-graphql/utils/RuleHelpers' {
  declare module.exports: any;
}

declare module 'codemirror-graphql/utils/Rules' {
  declare module.exports: any;
}

declare module 'codemirror-graphql/utils/runParser' {
  declare module.exports: any;
}

declare module 'codemirror-graphql/utils/SchemaReference' {
  declare module.exports: any;
}

declare module 'codemirror-graphql/variables/hint' {
  declare module.exports: any;
}

declare module 'codemirror-graphql/variables/lint' {
  declare module.exports: any;
}

declare module 'codemirror-graphql/variables/mode' {
  declare module.exports: any;
}

// Filename aliases
declare module 'codemirror-graphql/hint.js' {
  declare module.exports: $Exports<'codemirror-graphql/hint'>;
}
declare module 'codemirror-graphql/info.js' {
  declare module.exports: $Exports<'codemirror-graphql/info'>;
}
declare module 'codemirror-graphql/jump.js' {
  declare module.exports: $Exports<'codemirror-graphql/jump'>;
}
declare module 'codemirror-graphql/lint.js' {
  declare module.exports: $Exports<'codemirror-graphql/lint'>;
}
declare module 'codemirror-graphql/mode.js' {
  declare module.exports: $Exports<'codemirror-graphql/mode'>;
}
declare module 'codemirror-graphql/results/mode.js' {
  declare module.exports: $Exports<'codemirror-graphql/results/mode'>;
}
declare module 'codemirror-graphql/utils/CharacterStream.js' {
  declare module.exports: $Exports<'codemirror-graphql/utils/CharacterStream'>;
}
declare module 'codemirror-graphql/utils/collectVariables.js' {
  declare module.exports: $Exports<'codemirror-graphql/utils/collectVariables'>;
}
declare module 'codemirror-graphql/utils/forEachState.js' {
  declare module.exports: $Exports<'codemirror-graphql/utils/forEachState'>;
}
declare module 'codemirror-graphql/utils/getHintsAtPosition.js' {
  declare module.exports: $Exports<'codemirror-graphql/utils/getHintsAtPosition'>;
}
declare module 'codemirror-graphql/utils/getTokenAtPosition.js' {
  declare module.exports: $Exports<'codemirror-graphql/utils/getTokenAtPosition'>;
}
declare module 'codemirror-graphql/utils/getTypeInfo.js' {
  declare module.exports: $Exports<'codemirror-graphql/utils/getTypeInfo'>;
}
declare module 'codemirror-graphql/utils/hintList.js' {
  declare module.exports: $Exports<'codemirror-graphql/utils/hintList'>;
}
declare module 'codemirror-graphql/utils/info-addon.js' {
  declare module.exports: $Exports<'codemirror-graphql/utils/info-addon'>;
}
declare module 'codemirror-graphql/utils/jsonParse.js' {
  declare module.exports: $Exports<'codemirror-graphql/utils/jsonParse'>;
}
declare module 'codemirror-graphql/utils/jump-addon.js' {
  declare module.exports: $Exports<'codemirror-graphql/utils/jump-addon'>;
}
declare module 'codemirror-graphql/utils/objectValues.js' {
  declare module.exports: $Exports<'codemirror-graphql/utils/objectValues'>;
}
declare module 'codemirror-graphql/utils/onlineParser.js' {
  declare module.exports: $Exports<'codemirror-graphql/utils/onlineParser'>;
}
declare module 'codemirror-graphql/utils/RuleHelpers.js' {
  declare module.exports: $Exports<'codemirror-graphql/utils/RuleHelpers'>;
}
declare module 'codemirror-graphql/utils/Rules.js' {
  declare module.exports: $Exports<'codemirror-graphql/utils/Rules'>;
}
declare module 'codemirror-graphql/utils/runParser.js' {
  declare module.exports: $Exports<'codemirror-graphql/utils/runParser'>;
}
declare module 'codemirror-graphql/utils/SchemaReference.js' {
  declare module.exports: $Exports<'codemirror-graphql/utils/SchemaReference'>;
}
declare module 'codemirror-graphql/variables/hint.js' {
  declare module.exports: $Exports<'codemirror-graphql/variables/hint'>;
}
declare module 'codemirror-graphql/variables/lint.js' {
  declare module.exports: $Exports<'codemirror-graphql/variables/lint'>;
}
declare module 'codemirror-graphql/variables/mode.js' {
  declare module.exports: $Exports<'codemirror-graphql/variables/mode'>;
}
