// flow-typed signature: c642e187276de06b9138a62193f39aef
// flow-typed version: <<STUB>>/code-frame_v5.0.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'code-frame'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'code-frame' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'code-frame/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'code-frame/lib/index.js' {
  declare module.exports: $Exports<'code-frame/lib/index'>;
}
