// flow-typed signature: 2ade6165fb12dc05e6079275d6e5b667
// flow-typed version: <<STUB>>/deasync_v0.1.9/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'deasync'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'deasync' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'deasync/build' {
  declare module.exports: any;
}

declare module 'deasync/quick-test' {
  declare module.exports: any;
}

declare module 'deasync/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'deasync/build.js' {
  declare module.exports: $Exports<'deasync/build'>;
}
declare module 'deasync/index' {
  declare module.exports: $Exports<'deasync'>;
}
declare module 'deasync/index.js' {
  declare module.exports: $Exports<'deasync'>;
}
declare module 'deasync/quick-test.js' {
  declare module.exports: $Exports<'deasync/quick-test'>;
}
declare module 'deasync/test.js' {
  declare module.exports: $Exports<'deasync/test'>;
}
