// flow-typed signature: 7c97fdd26b694bd3de77d0bd0a7bdf64
// flow-typed version: <<STUB>>/find-config_v1.0.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'find-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'find-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'find-config/gulpfile' {
  declare module.exports: any;
}

declare module 'find-config/src/find-config' {
  declare module.exports: any;
}

declare module 'find-config/test/benchmark/find-config.bench' {
  declare module.exports: any;
}

declare module 'find-config/test/benchmark/findup-sync.bench' {
  declare module.exports: any;
}

declare module 'find-config/test/benchmark/index' {
  declare module.exports: any;
}

declare module 'find-config/test/benchmark/look-up.bench' {
  declare module.exports: any;
}

declare module 'find-config/test/find-config' {
  declare module.exports: any;
}

declare module 'find-config/test/fixtures/a/index' {
  declare module.exports: any;
}

declare module 'find-config/test/fixtures/b' {
  declare module.exports: any;
}

declare module 'find-config/test/fixtures/bbb' {
  declare module.exports: any;
}

// Filename aliases
declare module 'find-config/gulpfile.js' {
  declare module.exports: $Exports<'find-config/gulpfile'>;
}
declare module 'find-config/src/find-config.js' {
  declare module.exports: $Exports<'find-config/src/find-config'>;
}
declare module 'find-config/test/benchmark/find-config.bench.js' {
  declare module.exports: $Exports<'find-config/test/benchmark/find-config.bench'>;
}
declare module 'find-config/test/benchmark/findup-sync.bench.js' {
  declare module.exports: $Exports<'find-config/test/benchmark/findup-sync.bench'>;
}
declare module 'find-config/test/benchmark/index.js' {
  declare module.exports: $Exports<'find-config/test/benchmark/index'>;
}
declare module 'find-config/test/benchmark/look-up.bench.js' {
  declare module.exports: $Exports<'find-config/test/benchmark/look-up.bench'>;
}
declare module 'find-config/test/find-config.js' {
  declare module.exports: $Exports<'find-config/test/find-config'>;
}
declare module 'find-config/test/fixtures/a/index.js' {
  declare module.exports: $Exports<'find-config/test/fixtures/a/index'>;
}
declare module 'find-config/test/fixtures/b.js' {
  declare module.exports: $Exports<'find-config/test/fixtures/b'>;
}
declare module 'find-config/test/fixtures/bbb.js' {
  declare module.exports: $Exports<'find-config/test/fixtures/bbb'>;
}
