// flow-typed signature: 2c85f02885a1ade461a5ff42a8882e41
// flow-typed version: <<STUB>>/flow-runtime_v0.10.0/flow_v0.44.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-runtime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-runtime' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow-runtime/dist/flow-runtime.es2015' {
  declare module.exports: any;
}

declare module 'flow-runtime/dist/flow-runtime' {
  declare module.exports: any;
}

declare module 'flow-runtime/dist/flow-runtime.min' {
  declare module.exports: any;
}

declare module 'flow-runtime/dist/flow-runtime.umd' {
  declare module.exports: any;
}

declare module 'flow-runtime/test-polyfill' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flow-runtime/dist/flow-runtime.es2015.js' {
  declare module.exports: $Exports<'flow-runtime/dist/flow-runtime.es2015'>;
}
declare module 'flow-runtime/dist/flow-runtime.js' {
  declare module.exports: $Exports<'flow-runtime/dist/flow-runtime'>;
}
declare module 'flow-runtime/dist/flow-runtime.min.js' {
  declare module.exports: $Exports<'flow-runtime/dist/flow-runtime.min'>;
}
declare module 'flow-runtime/dist/flow-runtime.umd.js' {
  declare module.exports: $Exports<'flow-runtime/dist/flow-runtime.umd'>;
}
declare module 'flow-runtime/test-polyfill.js' {
  declare module.exports: $Exports<'flow-runtime/test-polyfill'>;
}
