// flow-typed signature: dd009f8849d6bd52864df24b658a943d
// flow-typed version: <<STUB>>/glob-parent_v5.0.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'glob-parent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'glob-parent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'glob-parent/index' {
  declare module.exports: $Exports<'glob-parent'>;
}
declare module 'glob-parent/index.js' {
  declare module.exports: $Exports<'glob-parent'>;
}
