// flow-typed signature: 3aadbb95ef5b0a6070a73d070b264c76
// flow-typed version: <<STUB>>/has-ansi_v3.0.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'has-ansi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'has-ansi' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'has-ansi/index' {
  declare module.exports: $Exports<'has-ansi'>;
}
declare module 'has-ansi/index.js' {
  declare module.exports: $Exports<'has-ansi'>;
}
