// flow-typed signature: eb734ebdcc78c775ceae9498d59e7a12
// flow-typed version: <<STUB>>/jest-runner-eslint_v0.7.4/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-runner-eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-runner-eslint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-runner-eslint/build/runner/index' {
  declare module.exports: any;
}

declare module 'jest-runner-eslint/build/runner/runESLint' {
  declare module.exports: any;
}

declare module 'jest-runner-eslint/build/utils/configOverrides' {
  declare module.exports: any;
}

declare module 'jest-runner-eslint/build/utils/getESLintOptions' {
  declare module.exports: any;
}

declare module 'jest-runner-eslint/build/utils/normalizeConfig' {
  declare module.exports: any;
}

declare module 'jest-runner-eslint/build/watchFixPlugin/index' {
  declare module.exports: any;
}

declare module 'jest-runner-eslint/watch-fix' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-runner-eslint/build/runner/index.js' {
  declare module.exports: $Exports<'jest-runner-eslint/build/runner/index'>;
}
declare module 'jest-runner-eslint/build/runner/runESLint.js' {
  declare module.exports: $Exports<'jest-runner-eslint/build/runner/runESLint'>;
}
declare module 'jest-runner-eslint/build/utils/configOverrides.js' {
  declare module.exports: $Exports<'jest-runner-eslint/build/utils/configOverrides'>;
}
declare module 'jest-runner-eslint/build/utils/getESLintOptions.js' {
  declare module.exports: $Exports<'jest-runner-eslint/build/utils/getESLintOptions'>;
}
declare module 'jest-runner-eslint/build/utils/normalizeConfig.js' {
  declare module.exports: $Exports<'jest-runner-eslint/build/utils/normalizeConfig'>;
}
declare module 'jest-runner-eslint/build/watchFixPlugin/index.js' {
  declare module.exports: $Exports<'jest-runner-eslint/build/watchFixPlugin/index'>;
}
declare module 'jest-runner-eslint/watch-fix.js' {
  declare module.exports: $Exports<'jest-runner-eslint/watch-fix'>;
}
