// flow-typed signature: d034cbf6983e2a73577ac4e5c46a37e9
// flow-typed version: <<STUB>>/jest-runner-eslint_v0.6.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-runner-eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-runner-eslint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-runner-eslint/build/getIgnoredPaths' {
  declare module.exports: any;
}

declare module 'jest-runner-eslint/build/index' {
  declare module.exports: any;
}

declare module 'jest-runner-eslint/build/runESLint' {
  declare module.exports: any;
}

declare module 'jest-runner-eslint/build/utils/getConfigFile' {
  declare module.exports: any;
}

declare module 'jest-runner-eslint/build/utils/getESLintConfig' {
  declare module.exports: any;
}

declare module 'jest-runner-eslint/build/utils/getESLintOptions' {
  declare module.exports: any;
}

declare module 'jest-runner-eslint/build/utils/getLocalESLint' {
  declare module.exports: any;
}

declare module 'jest-runner-eslint/build/utils/getLocalESLintPath' {
  declare module.exports: any;
}

declare module 'jest-runner-eslint/build/utils/normalizeConfig' {
  declare module.exports: any;
}

declare module 'jest-runner-eslint/build/utils/toTestResult' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-runner-eslint/build/getIgnoredPaths.js' {
  declare module.exports: $Exports<'jest-runner-eslint/build/getIgnoredPaths'>;
}
declare module 'jest-runner-eslint/build/index.js' {
  declare module.exports: $Exports<'jest-runner-eslint/build/index'>;
}
declare module 'jest-runner-eslint/build/runESLint.js' {
  declare module.exports: $Exports<'jest-runner-eslint/build/runESLint'>;
}
declare module 'jest-runner-eslint/build/utils/getConfigFile.js' {
  declare module.exports: $Exports<'jest-runner-eslint/build/utils/getConfigFile'>;
}
declare module 'jest-runner-eslint/build/utils/getESLintConfig.js' {
  declare module.exports: $Exports<'jest-runner-eslint/build/utils/getESLintConfig'>;
}
declare module 'jest-runner-eslint/build/utils/getESLintOptions.js' {
  declare module.exports: $Exports<'jest-runner-eslint/build/utils/getESLintOptions'>;
}
declare module 'jest-runner-eslint/build/utils/getLocalESLint.js' {
  declare module.exports: $Exports<'jest-runner-eslint/build/utils/getLocalESLint'>;
}
declare module 'jest-runner-eslint/build/utils/getLocalESLintPath.js' {
  declare module.exports: $Exports<'jest-runner-eslint/build/utils/getLocalESLintPath'>;
}
declare module 'jest-runner-eslint/build/utils/normalizeConfig.js' {
  declare module.exports: $Exports<'jest-runner-eslint/build/utils/normalizeConfig'>;
}
declare module 'jest-runner-eslint/build/utils/toTestResult.js' {
  declare module.exports: $Exports<'jest-runner-eslint/build/utils/toTestResult'>;
}
