// flow-typed signature: 2331cdbe8f125b1ef63a904828daf481
// flow-typed version: <<STUB>>/keymirror_v0.1.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'keymirror'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'keymirror' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'keymirror/index' {
  declare module.exports: $Exports<'keymirror'>;
}
declare module 'keymirror/index.js' {
  declare module.exports: $Exports<'keymirror'>;
}
