// flow-typed signature: d04e8aa3b5fa7556005fc3ab01431f0f
// flow-typed version: <<STUB>>/leven_v3.1.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'leven'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'leven' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'leven/index' {
  declare module.exports: $Exports<'leven'>;
}
declare module 'leven/index.js' {
  declare module.exports: $Exports<'leven'>;
}
