// flow-typed signature: 0a1e3cb0117fc5bfea23f90718f29b14
// flow-typed version: <<STUB>>/log-symbols_v2.2.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'log-symbols'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'log-symbols' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'log-symbols/browser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'log-symbols/browser.js' {
  declare module.exports: $Exports<'log-symbols/browser'>;
}
declare module 'log-symbols/index' {
  declare module.exports: $Exports<'log-symbols'>;
}
declare module 'log-symbols/index.js' {
  declare module.exports: $Exports<'log-symbols'>;
}
