// flow-typed signature: b6fe4040cf868a8b0b5f32d9ae2e318d
// flow-typed version: <<STUB>>/minimatch_v3.0.4/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'minimatch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'minimatch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'minimatch/minimatch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'minimatch/minimatch.js' {
  declare module.exports: $Exports<'minimatch/minimatch'>;
}
