// flow-typed signature: ad519941b638dfcb6cc23270b21158f1
// flow-typed version: <<STUB>>/node-ipc_v9.0.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-ipc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-ipc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-ipc/dao/client' {
  declare module.exports: any;
}

declare module 'node-ipc/dao/socketServer' {
  declare module.exports: any;
}

declare module 'node-ipc/entities/Defaults' {
  declare module.exports: any;
}

declare module 'node-ipc/entities/EventParser' {
  declare module.exports: any;
}

declare module 'node-ipc/example/rawBuffer/hello-client' {
  declare module.exports: any;
}

declare module 'node-ipc/example/rawBuffer/world.server' {
  declare module.exports: any;
}

declare module 'node-ipc/example/TCPSocket/basic/hello-client' {
  declare module.exports: any;
}

declare module 'node-ipc/example/TCPSocket/basic/world-server' {
  declare module.exports: any;
}

declare module 'node-ipc/example/TCPSocket/basicSync/hello-client' {
  declare module.exports: any;
}

declare module 'node-ipc/example/TCPSocket/basicSync/world-server' {
  declare module.exports: any;
}

declare module 'node-ipc/example/TCPSocket/Multi-Client-Broadcast/goodbye-client' {
  declare module.exports: any;
}

declare module 'node-ipc/example/TCPSocket/Multi-Client-Broadcast/hello-client' {
  declare module.exports: any;
}

declare module 'node-ipc/example/TCPSocket/Multi-Client-Broadcast/world-server' {
  declare module.exports: any;
}

declare module 'node-ipc/example/TCPSocket/rawBuffer/hello-client' {
  declare module.exports: any;
}

declare module 'node-ipc/example/TCPSocket/rawBuffer/world.server' {
  declare module.exports: any;
}

declare module 'node-ipc/example/TLSSocket/basic-local-only/hello-client' {
  declare module.exports: any;
}

declare module 'node-ipc/example/TLSSocket/basic-local-only/world-server' {
  declare module.exports: any;
}

declare module 'node-ipc/example/TLSSocket/basic-more-secure/hello-client' {
  declare module.exports: any;
}

declare module 'node-ipc/example/TLSSocket/basic-more-secure/world-server' {
  declare module.exports: any;
}

declare module 'node-ipc/example/TLSSocket/basic-most-secure/hello-client' {
  declare module.exports: any;
}

declare module 'node-ipc/example/TLSSocket/basic-most-secure/world-server' {
  declare module.exports: any;
}

declare module 'node-ipc/example/TLSSocket/basic/hello-client' {
  declare module.exports: any;
}

declare module 'node-ipc/example/TLSSocket/basic/world-server' {
  declare module.exports: any;
}

declare module 'node-ipc/example/TLSSocket/basicSync/hello-client' {
  declare module.exports: any;
}

declare module 'node-ipc/example/TLSSocket/basicSync/world-server' {
  declare module.exports: any;
}

declare module 'node-ipc/example/TLSSocket/Multi-Client-Broadcast-basic/goodbye-client' {
  declare module.exports: any;
}

declare module 'node-ipc/example/TLSSocket/Multi-Client-Broadcast-basic/hello-client' {
  declare module.exports: any;
}

declare module 'node-ipc/example/TLSSocket/Multi-Client-Broadcast-basic/world-server' {
  declare module.exports: any;
}

declare module 'node-ipc/example/TLSSocket/rawBuffer-only-works-with-most-secure/hello-client' {
  declare module.exports: any;
}

declare module 'node-ipc/example/TLSSocket/rawBuffer-only-works-with-most-secure/world.server' {
  declare module.exports: any;
}

declare module 'node-ipc/example/UDPSocket/basic/hello-client' {
  declare module.exports: any;
}

declare module 'node-ipc/example/UDPSocket/basic/world-server' {
  declare module.exports: any;
}

declare module 'node-ipc/example/UDPSocket/Multi-Client-Broadcast/goodbye-client' {
  declare module.exports: any;
}

declare module 'node-ipc/example/UDPSocket/Multi-Client-Broadcast/hello-client' {
  declare module.exports: any;
}

declare module 'node-ipc/example/UDPSocket/Multi-Client-Broadcast/world-server' {
  declare module.exports: any;
}

declare module 'node-ipc/example/UDPSocket/rawBuffer/hello-client' {
  declare module.exports: any;
}

declare module 'node-ipc/example/UDPSocket/rawBuffer/world.server' {
  declare module.exports: any;
}

declare module 'node-ipc/example/unixWindowsSocket/basic/hello-client' {
  declare module.exports: any;
}

declare module 'node-ipc/example/unixWindowsSocket/basic/world-server' {
  declare module.exports: any;
}

declare module 'node-ipc/example/unixWindowsSocket/basicSync/hello-client' {
  declare module.exports: any;
}

declare module 'node-ipc/example/unixWindowsSocket/basicSync/world-server' {
  declare module.exports: any;
}

declare module 'node-ipc/example/unixWindowsSocket/Multi-Client-Broadcast/goodbye-client' {
  declare module.exports: any;
}

declare module 'node-ipc/example/unixWindowsSocket/Multi-Client-Broadcast/hello-client' {
  declare module.exports: any;
}

declare module 'node-ipc/example/unixWindowsSocket/Multi-Client-Broadcast/world-server' {
  declare module.exports: any;
}

declare module 'node-ipc/example/unixWindowsSocket/rawBuffer/hello-client' {
  declare module.exports: any;
}

declare module 'node-ipc/example/unixWindowsSocket/rawBuffer/world.server' {
  declare module.exports: any;
}

declare module 'node-ipc/node-ipc' {
  declare module.exports: any;
}

declare module 'node-ipc/services/IPC' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-ipc/dao/client.js' {
  declare module.exports: $Exports<'node-ipc/dao/client'>;
}
declare module 'node-ipc/dao/socketServer.js' {
  declare module.exports: $Exports<'node-ipc/dao/socketServer'>;
}
declare module 'node-ipc/entities/Defaults.js' {
  declare module.exports: $Exports<'node-ipc/entities/Defaults'>;
}
declare module 'node-ipc/entities/EventParser.js' {
  declare module.exports: $Exports<'node-ipc/entities/EventParser'>;
}
declare module 'node-ipc/example/rawBuffer/hello-client.js' {
  declare module.exports: $Exports<'node-ipc/example/rawBuffer/hello-client'>;
}
declare module 'node-ipc/example/rawBuffer/world.server.js' {
  declare module.exports: $Exports<'node-ipc/example/rawBuffer/world.server'>;
}
declare module 'node-ipc/example/TCPSocket/basic/hello-client.js' {
  declare module.exports: $Exports<'node-ipc/example/TCPSocket/basic/hello-client'>;
}
declare module 'node-ipc/example/TCPSocket/basic/world-server.js' {
  declare module.exports: $Exports<'node-ipc/example/TCPSocket/basic/world-server'>;
}
declare module 'node-ipc/example/TCPSocket/basicSync/hello-client.js' {
  declare module.exports: $Exports<'node-ipc/example/TCPSocket/basicSync/hello-client'>;
}
declare module 'node-ipc/example/TCPSocket/basicSync/world-server.js' {
  declare module.exports: $Exports<'node-ipc/example/TCPSocket/basicSync/world-server'>;
}
declare module 'node-ipc/example/TCPSocket/Multi-Client-Broadcast/goodbye-client.js' {
  declare module.exports: $Exports<'node-ipc/example/TCPSocket/Multi-Client-Broadcast/goodbye-client'>;
}
declare module 'node-ipc/example/TCPSocket/Multi-Client-Broadcast/hello-client.js' {
  declare module.exports: $Exports<'node-ipc/example/TCPSocket/Multi-Client-Broadcast/hello-client'>;
}
declare module 'node-ipc/example/TCPSocket/Multi-Client-Broadcast/world-server.js' {
  declare module.exports: $Exports<'node-ipc/example/TCPSocket/Multi-Client-Broadcast/world-server'>;
}
declare module 'node-ipc/example/TCPSocket/rawBuffer/hello-client.js' {
  declare module.exports: $Exports<'node-ipc/example/TCPSocket/rawBuffer/hello-client'>;
}
declare module 'node-ipc/example/TCPSocket/rawBuffer/world.server.js' {
  declare module.exports: $Exports<'node-ipc/example/TCPSocket/rawBuffer/world.server'>;
}
declare module 'node-ipc/example/TLSSocket/basic-local-only/hello-client.js' {
  declare module.exports: $Exports<'node-ipc/example/TLSSocket/basic-local-only/hello-client'>;
}
declare module 'node-ipc/example/TLSSocket/basic-local-only/world-server.js' {
  declare module.exports: $Exports<'node-ipc/example/TLSSocket/basic-local-only/world-server'>;
}
declare module 'node-ipc/example/TLSSocket/basic-more-secure/hello-client.js' {
  declare module.exports: $Exports<'node-ipc/example/TLSSocket/basic-more-secure/hello-client'>;
}
declare module 'node-ipc/example/TLSSocket/basic-more-secure/world-server.js' {
  declare module.exports: $Exports<'node-ipc/example/TLSSocket/basic-more-secure/world-server'>;
}
declare module 'node-ipc/example/TLSSocket/basic-most-secure/hello-client.js' {
  declare module.exports: $Exports<'node-ipc/example/TLSSocket/basic-most-secure/hello-client'>;
}
declare module 'node-ipc/example/TLSSocket/basic-most-secure/world-server.js' {
  declare module.exports: $Exports<'node-ipc/example/TLSSocket/basic-most-secure/world-server'>;
}
declare module 'node-ipc/example/TLSSocket/basic/hello-client.js' {
  declare module.exports: $Exports<'node-ipc/example/TLSSocket/basic/hello-client'>;
}
declare module 'node-ipc/example/TLSSocket/basic/world-server.js' {
  declare module.exports: $Exports<'node-ipc/example/TLSSocket/basic/world-server'>;
}
declare module 'node-ipc/example/TLSSocket/basicSync/hello-client.js' {
  declare module.exports: $Exports<'node-ipc/example/TLSSocket/basicSync/hello-client'>;
}
declare module 'node-ipc/example/TLSSocket/basicSync/world-server.js' {
  declare module.exports: $Exports<'node-ipc/example/TLSSocket/basicSync/world-server'>;
}
declare module 'node-ipc/example/TLSSocket/Multi-Client-Broadcast-basic/goodbye-client.js' {
  declare module.exports: $Exports<'node-ipc/example/TLSSocket/Multi-Client-Broadcast-basic/goodbye-client'>;
}
declare module 'node-ipc/example/TLSSocket/Multi-Client-Broadcast-basic/hello-client.js' {
  declare module.exports: $Exports<'node-ipc/example/TLSSocket/Multi-Client-Broadcast-basic/hello-client'>;
}
declare module 'node-ipc/example/TLSSocket/Multi-Client-Broadcast-basic/world-server.js' {
  declare module.exports: $Exports<'node-ipc/example/TLSSocket/Multi-Client-Broadcast-basic/world-server'>;
}
declare module 'node-ipc/example/TLSSocket/rawBuffer-only-works-with-most-secure/hello-client.js' {
  declare module.exports: $Exports<'node-ipc/example/TLSSocket/rawBuffer-only-works-with-most-secure/hello-client'>;
}
declare module 'node-ipc/example/TLSSocket/rawBuffer-only-works-with-most-secure/world.server.js' {
  declare module.exports: $Exports<'node-ipc/example/TLSSocket/rawBuffer-only-works-with-most-secure/world.server'>;
}
declare module 'node-ipc/example/UDPSocket/basic/hello-client.js' {
  declare module.exports: $Exports<'node-ipc/example/UDPSocket/basic/hello-client'>;
}
declare module 'node-ipc/example/UDPSocket/basic/world-server.js' {
  declare module.exports: $Exports<'node-ipc/example/UDPSocket/basic/world-server'>;
}
declare module 'node-ipc/example/UDPSocket/Multi-Client-Broadcast/goodbye-client.js' {
  declare module.exports: $Exports<'node-ipc/example/UDPSocket/Multi-Client-Broadcast/goodbye-client'>;
}
declare module 'node-ipc/example/UDPSocket/Multi-Client-Broadcast/hello-client.js' {
  declare module.exports: $Exports<'node-ipc/example/UDPSocket/Multi-Client-Broadcast/hello-client'>;
}
declare module 'node-ipc/example/UDPSocket/Multi-Client-Broadcast/world-server.js' {
  declare module.exports: $Exports<'node-ipc/example/UDPSocket/Multi-Client-Broadcast/world-server'>;
}
declare module 'node-ipc/example/UDPSocket/rawBuffer/hello-client.js' {
  declare module.exports: $Exports<'node-ipc/example/UDPSocket/rawBuffer/hello-client'>;
}
declare module 'node-ipc/example/UDPSocket/rawBuffer/world.server.js' {
  declare module.exports: $Exports<'node-ipc/example/UDPSocket/rawBuffer/world.server'>;
}
declare module 'node-ipc/example/unixWindowsSocket/basic/hello-client.js' {
  declare module.exports: $Exports<'node-ipc/example/unixWindowsSocket/basic/hello-client'>;
}
declare module 'node-ipc/example/unixWindowsSocket/basic/world-server.js' {
  declare module.exports: $Exports<'node-ipc/example/unixWindowsSocket/basic/world-server'>;
}
declare module 'node-ipc/example/unixWindowsSocket/basicSync/hello-client.js' {
  declare module.exports: $Exports<'node-ipc/example/unixWindowsSocket/basicSync/hello-client'>;
}
declare module 'node-ipc/example/unixWindowsSocket/basicSync/world-server.js' {
  declare module.exports: $Exports<'node-ipc/example/unixWindowsSocket/basicSync/world-server'>;
}
declare module 'node-ipc/example/unixWindowsSocket/Multi-Client-Broadcast/goodbye-client.js' {
  declare module.exports: $Exports<'node-ipc/example/unixWindowsSocket/Multi-Client-Broadcast/goodbye-client'>;
}
declare module 'node-ipc/example/unixWindowsSocket/Multi-Client-Broadcast/hello-client.js' {
  declare module.exports: $Exports<'node-ipc/example/unixWindowsSocket/Multi-Client-Broadcast/hello-client'>;
}
declare module 'node-ipc/example/unixWindowsSocket/Multi-Client-Broadcast/world-server.js' {
  declare module.exports: $Exports<'node-ipc/example/unixWindowsSocket/Multi-Client-Broadcast/world-server'>;
}
declare module 'node-ipc/example/unixWindowsSocket/rawBuffer/hello-client.js' {
  declare module.exports: $Exports<'node-ipc/example/unixWindowsSocket/rawBuffer/hello-client'>;
}
declare module 'node-ipc/example/unixWindowsSocket/rawBuffer/world.server.js' {
  declare module.exports: $Exports<'node-ipc/example/unixWindowsSocket/rawBuffer/world.server'>;
}
declare module 'node-ipc/node-ipc.js' {
  declare module.exports: $Exports<'node-ipc/node-ipc'>;
}
declare module 'node-ipc/services/IPC.js' {
  declare module.exports: $Exports<'node-ipc/services/IPC'>;
}
