// flow-typed signature: ab83a04d76f98d02d2714231b8a0e223
// flow-typed version: <<STUB>>/parse-glob_v3.0.4/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parse-glob'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'parse-glob' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'parse-glob/index' {
  declare module.exports: $Exports<'parse-glob'>;
}
declare module 'parse-glob/index.js' {
  declare module.exports: $Exports<'parse-glob'>;
}
