// flow-typed signature: cec4a769b0838f3a58753f261fe7001c
// flow-typed version: <<STUB>>/sane_v2.5.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sane'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sane' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sane/src/cli' {
  declare module.exports: any;
}

declare module 'sane/src/common' {
  declare module.exports: any;
}

declare module 'sane/src/fsevents_watcher' {
  declare module.exports: any;
}

declare module 'sane/src/node_watcher' {
  declare module.exports: any;
}

declare module 'sane/src/poll_watcher' {
  declare module.exports: any;
}

declare module 'sane/src/utils/recrawl-warning-dedupe' {
  declare module.exports: any;
}

declare module 'sane/src/watchman_client' {
  declare module.exports: any;
}

declare module 'sane/src/watchman_watcher' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sane/index' {
  declare module.exports: $Exports<'sane'>;
}
declare module 'sane/index.js' {
  declare module.exports: $Exports<'sane'>;
}
declare module 'sane/src/cli.js' {
  declare module.exports: $Exports<'sane/src/cli'>;
}
declare module 'sane/src/common.js' {
  declare module.exports: $Exports<'sane/src/common'>;
}
declare module 'sane/src/fsevents_watcher.js' {
  declare module.exports: $Exports<'sane/src/fsevents_watcher'>;
}
declare module 'sane/src/node_watcher.js' {
  declare module.exports: $Exports<'sane/src/node_watcher'>;
}
declare module 'sane/src/poll_watcher.js' {
  declare module.exports: $Exports<'sane/src/poll_watcher'>;
}
declare module 'sane/src/utils/recrawl-warning-dedupe.js' {
  declare module.exports: $Exports<'sane/src/utils/recrawl-warning-dedupe'>;
}
declare module 'sane/src/watchman_client.js' {
  declare module.exports: $Exports<'sane/src/watchman_client'>;
}
declare module 'sane/src/watchman_watcher.js' {
  declare module.exports: $Exports<'sane/src/watchman_watcher'>;
}
